name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸš€ Checkout repository
      uses: actions/checkout@v2

    - name: ğŸ“¦ Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14  # Utilisez la version de Node.js que vous utilisez pour dÃ©velopper

    - name: â¬‡ï¸ Install dependencies
      run: npm install

    - name: ğŸ› ï¸ Build and test
      run: |
        npm run build  # Remplacez par la commande de build de votre application
        npm test       # Remplacez par la commande de test de votre application

    - name: ğŸ Workflow completed!
      run: echo "âœ… Node.js CI workflow completed successfully."
